version: "3.8"
services:
  openvoice-api:
    image: openvoice-api-python
    container_name: openvoice
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - "SPEAKERS=cerbinou"
      - "MODEL_LANGUAGES_V2=FR"
      - "MODEL_LANGUAGES_V1="
      - "DEFAULT_LANGUAGE=FR"
      - "LOG_LEVEL=INFO"
    ports:
      - "8381:5000/tcp"
    command:
      - python3 
      - app.py
    volumes:
      - /mnt/e/workspace/my-scripts/cerbinou/tts/speakers:/app/speakers:rw
      - /mnt/e/workspace/my-scripts/cerbinou/tts/processed:/app/processed:rw
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper
    restart: always
    environment:
      - "ASR_MODEL=base"
      - "ASR_ENGINE=openai_whisper"
    ports:
      - "9000:9000/tcp"  
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]