services:
  ffxivv-notifier:
    build:
      context: notifier
      dockerfile: Dockerfile
    env_file: /etc/default/ffxivv
    container_name: ffxivv-notifier
    networks:
    - traefik
    - postgres

networks:
  postgres:
    name: postgres
    external: true
  traefik:
    name: traefik
    external: true
