services:

  postgres:
    image: ghcr.io/immich-app/postgres:17-vectorchord0.4.2-pgvectors0.3.0
    container_name: postgres
    restart: unless-stopped
    shm_size: 1gb
    env_file: /etc/default/postgresql
    ports:
      - 5432:5432
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - /home/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres
#    command: >
#      postgres
#      -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all -c max_connections=200
  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    restart: unless-stopped
    networks:
    - postgres


networks:
  postgres:
    driver: bridge
    name: postgres
