services:

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    env_file: /etc/default/zabbix
    ports:
      - 10051:10051
    networks:
     - zabbix
     - postgres
  web:
    image: zabbix/zabbix-web-apache-pgsql:latest
    container_name: zabbix
    restart: unless-stopped
    env_file: /etc/default/zabbix
    ports:
      - 45123:8080
    labels:
      - "traefik.enable=true"
    networks:
      - traefik
      - zabbix
      - postgres
  agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    restart: unless-stopped
    env_file: /etc/default/zabbix
    ports:
      - 10050:10050
    networks:
      - zabbix
    depends_on:
      - zabbix-server

networks:
  traefik:
    name: traefik
    external: true
  zabbix:
    driver: bridge
    name: zabbix
  postgres:
    name: postgres
    external: true
