services:

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    env_file: /etc/default/zabbix
    ports:
      - 10050:10050
      - 10051:10051
    networks:
     - zabbix

  web:
    image: zabbix/zabbix-web-apache-pgsql:latest
    container_name: zabbix
    restart: unless-stopped
    env_file: /etc/default/zabbix
    ports:
      - 45123:8080
    labels:
      - "traefik.enable=true"
    networks:
      - traefik
      - zabbix
#  agent:
#    image: zabbix/zabbix-agent2:latest
#    container_name: zabbix-agent
#    restart: unless-stopped
#    ports:
#      - 10051:10051
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - zabbix

  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    restart: unless-stopped
    env_file: /etc/default/zabbix
    volumes:
      - /home/zabbix/postgres/data:/var/lib/postgresql/data
    networks:
      - zabbix

networks:
  traefik:
    driver: bridge
    name: traefik
    external: true
  zabbix:
    driver: bridge
    name: zabbix
