version: "2.1"
services:
  blocky:
    image: adi3000/blocky:fb-dns-cache-switch
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Paris # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - /etc/blocky/config.yml:/app/config.yml
      - /etc/blocky/blacklists:/app/blacklists/
      - /etc/blocky/whitelists:/app/whitelists/
  blocky-frontend:
    depends_on:
      - blocky
    image: ghcr.io/mozart409/blocky-frontend:latest
    ports:
      - '4080:80'
