version: "3.3"
services:
  blocky:
    image: adi3000/blocky:fb-dns-switch-and-cache #adi3000/blocky:fb-dns-cache-switch
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Paris # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - /etc/blocky/config.yml:/app/config.yml
      - /etc/blocky/blacklists:/app/blacklists/
      - /etc/blocky/whitelists:/app/whitelists/
    labels:
      - "traefik.enable=true"
  blocky-frontend:
    depends_on:
      - blocky
    image: adi3000/blocky-frontend:main
    ports:
      - '4080:80'
    labels:
      - "traefik.enable=true"

