services:
  nextcloud:
    image: nextcloud:stable-apache
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 11220:80
    volumes:
      - /etc/nextcloud:/var/www/html/config
      - /home/adi/git/my-scripts/docker/nextcloud/apache/conf-enabled/nfs-tweak.conf:/etc/apache2/conf-enabled/nfs-tweak.conf
      - /mnt/nanopi/data/nextcloud/owncloud/data:/var/www/html/data
      - /mnt/nanopi/data/nextcloud/shared:/media
      - /mnt/nanopi/media/Downloads:/media/Downloads
      - /home/adi/git/my-scripts/docker/nextcloud/docker-entrypoint-hooks.d:/docker-entrypoint-hooks.d
    labels:
      - "traefik.enable=true"
    networks:
      - traefik
      - ldap
      - postgres
    env_file: /etc/default/nextcloud

  nextcloud-cron:
    image: nextcloud:stable-apache
    container_name: nextcloud-cron
    restart: always
    command: ["busybox","crond","-f","-L","/dev/stdout"]
    volumes:
      - /etc/nextcloud:/var/www/html/config
      - /mnt/nanopi/data/nextcloud/owncloud/data:/var/www/html/data
      - /mnt/nanopi/data/nextcloud/shared:/media
      - /mnt/nanopi/media/Downloads:/media/Downloads
    env_file: /etc/default/nextcloud
    environment:
      - NEXTCLOUD_UPDATE=1
    networks:
      - postgres
networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
  postgres:
    name: postgres
    external: true
