services:
  traefik:
    image: "traefik:v2.10"
    restart: always
    container_name: "traefik"
    ports:
    - "${PUB_FO}:80:80"
    - "${PUB_FO}:443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/etc/traefik:/etc/traefik:ro"
    - "/etc/letsencrypt:/etc/certs:ro"
    networks:
    - traefik

networks:
  traefik:
    driver: bridge
    name: traefik
